metadata:
    format: Lava-Test Test Definition 1.0
    name: ifconfig
    description: "Execute ifconfig"
    maintainer:
        - oliver.westermann@cognex.com

run:
    steps:
        - ifconfig